// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Retry() {
  return window['go']['main']['App']['Retry']();
}

export function SaveResultSize(arg1, arg2) {
  return window['go']['main']['App']['SaveResultSize'](arg1, arg2);
}

export function SendPrompt(arg1) {
  return window['go']['main']['App']['SendPrompt'](arg1);
}
