// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Retry():Promise<void>;

export function SaveResultSize(arg1:number,arg2:number):Promise<void>;

export function SendPrompt(arg1:string):Promise<void>;
