// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FetchModels(arg1:string,arg2:string):Promise<Array<string>>;

export function GetConfig():Promise<main.Config>;

export function Retry():Promise<void>;

export function SaveResultSize(arg1:number,arg2:number):Promise<void>;

export function SaveSettings(arg1:main.Config):Promise<string>;

export function SendPrompt(arg1:string):Promise<void>;
